<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <RootNamespace>NavCalc.App</RootNamespace>
    <AssemblyName>NavCalc</AssemblyName>
    <LangVersion>latest</LangVersion>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NavCalc.Core\NavCalc.Core.csproj" />
  </ItemGroup>

</Project>
